### ISSUE TITLE
Traceback issue:

### ISSUE THREAD

**Issue by singhaniashrinkhala** [pkumza/LibRadar#21]
For some of the APKs, I get this:

`Traceback (most recent call last):
  File "LibRadar/libradar.py", line 215, in <module>
    res = lrd.analyse()
  File "LibRadar/libradar.py", line 195, in analyse
    self.unzip()
  File "LibRadar/libradar.py", line 87, in unzip
    zf = zipfile.ZipFile(self.apk_path, mode='r')
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

`

**Comment by pkumza** [comment]
As we all know that apk file is a kind of Zip.
you could use zip tools to unzip any apk file.

If an apk could not be unzipped, it must be broken.
