### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Drjacky** [pkumza/LibRadar#62]
I'm using `pip` version 18.1
And when run `pip installs LibRadar` command, I get below error:

> Command "python setup.py egg_info" failed with error code 1 in C:\Users\DRF4E5~1
> .JAC\AppData\Local\Temp\pip-install-2fiod06h\Libradar\

```javascript
--- Logging error ---
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\pip\_internal\cli\base_command.py", lin
e 143, in main
    status = self.run(options, args)
  File "c:\python36-32\lib\site-packages\pip\_internal\commands\install.py", lin
e 318, in run
    resolver.resolve(requirement_set)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 102, in
 resolve
    self._resolve_one(requirement_set, req)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 256, in
 _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 209, in
 _get_abstract_dist_for
    self.require_hashes
  File "c:\python36-32\lib\site-packages\pip\_internal\operations\prepare.py", l
ine 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\python36-32\lib\site-packages\pip\_internal\operations\prepare.py", l
ine 126, in prep_for_dist
    self.req.run_egg_info()
  File "c:\python36-32\lib\site-packages\pip\_internal\req\req_install.py", line
 473, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\misc.py", line 705,
 in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" f
ailed with error code 1 in C:\Users\DRF4E5~1.JAC\AppData\Local\Temp\pip-install-
itj9d4nx\Libradar\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "c:\python36-32\lib\logging\handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\logging.py", line 1
22, in _open
    ensure_dir(os.path.dirname(self.baseFilename))
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\misc.py", line 89,
in ensure_dir
    os.makedirs(path)
  File "c:\python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'F:\\'
Call stack:
  File "c:\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-32\Scripts\pip.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python36-32\lib\site-packages\pip\_internal\__init__.py", line 78, in
 main
    return command.main(cmd_args)
  File "c:\python36-32\lib\site-packages\pip\_internal\cli\base_command.py", lin
e 154, in main
    logger.critical(str(exc))
Message: 'Command "python setup.py egg_info" failed with error code 1 in C:\\Use
rs\\DRF4E5~1.JAC\\AppData\\Local\\Temp\\pip-install-itj9d4nx\\Libradar\\'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\pip\_internal\cli\base_command.py", lin
e 143, in main
    status = self.run(options, args)
  File "c:\python36-32\lib\site-packages\pip\_internal\commands\install.py", lin
e 318, in run
    resolver.resolve(requirement_set)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 102, in
 resolve
    self._resolve_one(requirement_set, req)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 256, in
 _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\python36-32\lib\site-packages\pip\_internal\resolve.py", line 209, in
 _get_abstract_dist_for
    self.require_hashes
  File "c:\python36-32\lib\site-packages\pip\_internal\operations\prepare.py", l
ine 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\python36-32\lib\site-packages\pip\_internal\operations\prepare.py", l
ine 126, in prep_for_dist
    self.req.run_egg_info()
  File "c:\python36-32\lib\site-packages\pip\_internal\req\req_install.py", line
 473, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\misc.py", line 705,
 in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" f
ailed with error code 1 in C:\Users\DRF4E5~1.JAC\AppData\Local\Temp\pip-install-
itj9d4nx\Libradar\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\logging\handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "c:\python36-32\lib\logging\handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\logging.py", line 1
22, in _open
    ensure_dir(os.path.dirname(self.baseFilename))
  File "c:\python36-32\lib\site-packages\pip\_internal\utils\misc.py", line 89,
in ensure_dir
    os.makedirs(path)
  File "c:\python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'F:\\'
Call stack:
  File "c:\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-32\Scripts\pip.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python36-32\lib\site-packages\pip\_internal\__init__.py", line 78, in
 main
    return command.main(cmd_args)
  File "c:\python36-32\lib\site-packages\pip\_internal\cli\base_command.py", lin
e 155, in main
    logger.debug('Exception information:', exc_info=True)
Message: 'Exception information:'
Arguments: ()
```

**Comment by pkumza** [comment]
Use python2 instead
