### ISSUE TITLE
Python Script Not working

### ISSUE THREAD

**Issue by Sh-Amir** [pkumza/LibRadar#66]
Hello there, 

I tried to run your script on a sample app, therefore, I ran the script as it mentioned in the usage part: 

 python LibRadar/libradar.py test.apk

but I got the following error:

`Traceback (most recent call last):
  File "LibRadar/libradar.py", line 232, in <module>
    res = lrd.compare()
  File "LibRadar/libradar.py", line 220, in compare
    self.tree.get_repackage_main(res, self.hex_sha256)
  File "/Users/amirsharif/Desktop/HackingTools/LibRadar/LibRadar/dex_tree.py", line 411, in get_repackage_main
    self.db_rep.zadd("apk_weight", ret_length, hex_sha256 )
  File "/anaconda2/lib/python2.7/site-packages/redis/client.py", line 2388, in zadd
    for pair in iteritems(mapping):
  File "/anaconda2/lib/python2.7/site-packages/redis/_compat.py", line 81, in iteritems
    return x.iteritems()
AttributeError: 'int' object has no attribute 'iteritems'`

Thanks in advance

**Comment by pkumza** [comment]
Please try https://github.com/pkumza/LiteRadar instead,
or contact Email haoyuwang AT bupt.edu.cn
