### ISSUE TITLE
any idea about the  redis  error when get data?

### ISSUE THREAD

**Issue by butterl** [pkumza/LibRadar#69]
Hi, 
I tried to see the different output of LibRadar and LiteRadar，and add more data and tag to export . After I configured redis and the dumped database ， it seems somthing wrong  tookplace  in attribute not match, any idea if I missed something？

The code I'm using is the master，and the datasets are the dropbox one

```
butter@ubuntu18.04:~/code/LibRadar/LibRadar$ python libradar.py  com.ss.android.ugc.aweme.apk
Traceback (most recent call last):
  File "libradar.py", line 232, in <module>
    res = lrd.compare()
  File "libradar.py", line 220, in compare
    self.tree.get_repackage_main(res, self.hex_sha256)
  File "/home/butter/code/LibRadar/LibRadar/dex_tree.py", line 411, in get_repackage_main
    self.db_rep.zadd("apk_weight", ret_length, hex_sha256 )
  File "/home/butter/.local/lib/python2.7/site-packages/redis/client.py", line 2650, in zadd
    for pair in iteritems(mapping):
  File "/home/butter/.local/lib/python2.7/site-packages/redis/_compat.py", line 132, in iteritems
    return x.iteritems()
AttributeError: 'int' object has no attribute 'iteritems'
```

**Comment by pkumza** [comment]
Sorry, it's been 4 year so I don't know what's wrong with this. Looks like the problem of redis client.

For the other question

> What's the different between LibRadar and LiteRadar?

They are almost the same, except some long tail results

- lib1: 10000 samples
- lib2: 5000 samples
- lib3: 2000 samples
...
- lib77: 10 samples
- lib78: 9 samples
- lib79: 4 samples
- lib80: 1 sample
- lib81: 1 sample
- lib82: 1 sample

LiteRadar just remove lib77,lib78,lib79,lib80,lib81,lib82 from the database.
and these libs has low probability to be a real library.
