### ISSUE TITLE
Running into an error

### ISSUE THREAD

**Issue by chenju2k6** [pkumza/LibRadar#76]
$ python2 LibRadar/libradar.py ../obf_apk_original/com.llamacorp.equate.apk
Traceback (most recent call last):
  File "LibRadar/libradar.py", line 232, in <module>
    res = lrd.compare()
  File "LibRadar/libradar.py", line 220, in compare
    self.tree.get_repackage_main(res, self.hex_sha256)
  File "/home/cju/tpl/LibRadar/LibRadar/dex_tree.py", line 411, in get_repackage_main
    self.db_rep.zadd("apk_weight", ret_length, hex_sha256 )
  File "/home/cju/.local/lib/python2.7/site-packages/redis/client.py", line 2685, in zadd
    for pair in iteritems(mapping):
  File "/home/cju/.local/lib/python2.7/site-packages/redis/_compat.py", line 133, in iteritems
    return x.iteritems()
AttributeError: 'int' object has no attribute 'iteritems'

**Comment by pkumza** [comment]
It seems that the error was thrown by Redis.
Have you load the d.tar.gz from dropbox?

**Comment by Hatzky** [comment]
The error is thrown because of the redis version you installed with pip. Check if you installed version 2.10.5 with (pip install redis==2.10.5), as well as Python 2.7.12, which should fix this error. It can be a bit confusing because you need redis 2.10.5 and redis-server version 3.2.5.
